// backend/src/modules/reports/reports.routes.js
// ══════════════════════════════════════════════
// OWNER: NEERAJ   —   built in Phase 6
// Vishwajeet: do not edit this file.
// ══════════════════════════════════════════════
import { Router } from 'express';

const router = Router();

// The single POST report endpoint (§6.6). Mounted at /api/reports in
// app.js. The review queue that consumes these reports is a separate
// module (admin, Phase 8, Vishwajeet). Add Phase 6 routes here.

export default router;
