// backend/src/modules/notifications/notifications.routes.js
// ══════════════════════════════════════════════
// OWNER: NEERAJ   —   built in Phase 5
// Vishwajeet: do not edit this file.
// ══════════════════════════════════════════════
import { Router } from 'express';

const router = Router();

// Read side only (list, unread-count, mark-read). Mounted at
// /api/notifications in app.js. Writes come from utils/notify.js,
// not from this module. Add Phase 5 routes here; never in app.js.

export default router;
