// backend/src/modules/admin/admin.routes.js
// ══════════════════════════════════════════════
// OWNER: VISHWAJEET   —   built in Phase 8
// Neeraj: do not edit this file.
// ══════════════════════════════════════════════
import { Router } from 'express';

const router = Router();

// Moderation queue. Mounted at /api/admin in app.js. Every route in
// here must sit behind requireAuth plus an is_admin check — this is the
// one module where a missing guard exposes other people's reports.

export default router;
