// backend/src/modules/auth/auth.service.js
// ══════════════════════════════════════════════
// OWNER: VISHWAJEET   —   existing module
// Neeraj: do not edit this file.
// ══════════════════════════════════════════════
//
// Placeholder. Nothing imports this file yet; auth.controller.js talks
// to Supabase directly. Left in place so the banner records ownership.
