// backend/src/modules/auth/auth.routes.js
// ══════════════════════════════════════════════
// OWNER: VISHWAJEET   —   existing module
// Neeraj: do not edit this file.
// ══════════════════════════════════════════════
import express from 'express';
import {
    requestOtp,
    verifyOtp,
    completeOnboarding,
    demoLogin,
    loginWithPassword,
    setPassword,
    getPasswordStatus,
} from './auth.controller.js';
import requireAuth from '../../middleware/requireAuth.js';

const router = express.Router();

// POST /api/auth/request-otp
router.post('/request-otp', requestOtp);

// POST /api/auth/verify-otp
router.post('/verify-otp', verifyOtp);

// POST /api/auth/onboarding
//
// 🔒 requireAuth is the security fix, not a convenience. Without it the handler
// took the target user's id from the request body, so any caller could complete
// or overwrite any student's profile — and now that this endpoint also sets the
// account password, that would be account takeover. The token is the ONLY thing
// that says whose profile this is.
//
// ⚠️ Breaking for any client that does not send an Authorization header. See
// docs/CHANGELOG.md — the web onboarding page must ship its token fix in the
// same window or signup returns 401.
router.post('/onboarding', requireAuth, completeOnboarding);

// POST /api/auth/demo-login 
router.post('/demo-login', demoLogin);

// POST /api/auth/login-password
//
// Deliberately NOT behind requireAuth — this is how a student gets a token in
// the first place. It is also the only unauthenticated route in this backend
// that touches a credential, which is why the lockout in the controller runs
// before anything else and why every failure returns one identical body.
router.post('/login-password', loginWithPassword);

// POST /api/auth/set-password
//
// requireAuth is the whole authorisation model here: the password belongs to
// req.user.id and there is no target parameter to tamper with. Changing an
// existing password additionally needs current_password — see the controller.
router.post('/set-password', requireAuth, setPassword);

// GET /api/auth/password-status
//
// Answers only about the caller's own account. Never take a user id here — a
// public "does this account have a password?" oracle would be an enumeration
// primitive on a route that has no business being one.
router.get('/password-status', requireAuth, getPasswordStatus);

export default router;