// backend/src/app.js
// ══════════════════════════════════════════════
// OWNER: VISHWAJEET   —   built in Phase 0
// Neeraj: do not edit this file.
// ══════════════════════════════════════════════
//
// ⛔ FROZEN. Every route mount for every planned module is already here.
// If you need a new endpoint, add it inside your own module's routes file.
// If you genuinely need a new mount, message Vishwajeet — do not edit this.

import express from 'express';
import cors from 'cors';

// --- existing ---
import authRoutes from './modules/auth/auth.routes.js';
import productsRoutes from './modules/products/products.routes.js';
import messagesRoutes from './modules/messages/messages.routes.js';
import universitiesRoutes from './modules/university/university.routes.js';
import academicRoutes from './modules/academic/academic.routes.js';

// --- new: NEERAJ owns these files ---
import userRoutes from './modules/user/user.routes.js';
import socialRoutes from './modules/social/social.routes.js';
import notificationsRoutes from './modules/notifications/notifications.routes.js';
import reportsRoutes from './modules/reports/reports.routes.js';

// --- new: VISHWAJEET owns these files ---
import postsRoutes from './modules/posts/posts.routes.js';
import adminRoutes from './modules/admin/admin.routes.js';

const app = express();

app.use(cors());
app.use(express.json());

// A simple health check route
app.get('/api/health', (req, res) => {
    res.status(200).json({ status: 'Success', message: 'Yahora backend is up and running! 🚀...' });
});

app.get('/', (req, res) => {
    res.send('Yahora API is successfully running! 🚀...');
});

// --- existing ---
app.use('/api/auth',          authRoutes);
app.use('/api/products',      productsRoutes);
app.use('/api/messages',      messagesRoutes);
app.use('/api/universities',  universitiesRoutes);
app.use('/api/academic',      academicRoutes);

// Legacy singular mount, pre-dating this plan. The four existing user
// endpoints (dashboard, profile, avatar, public) are live at /api/user
// in both web and mobile, so this stays. New work uses /api/users below.
app.use('/api/user',          userRoutes);

// --- new: NEERAJ owns these files ---
app.use('/api/users',         userRoutes);          // usernames, search
app.use('/api/users',         socialRoutes);        // follows, blocks, privacy
app.use('/api/notifications', notificationsRoutes);
app.use('/api/reports',       reportsRoutes);

// --- new: VISHWAJEET owns these files ---
app.use('/api/posts',         postsRoutes);
app.use('/api/admin',         adminRoutes);

export default app;
