// backend/src/modules/user/user.routes.js
// ══════════════════════════════════════════════
// OWNER: NEERAJ   —   built in Phase 1
// Vishwajeet: do not edit this file.
// ══════════════════════════════════════════════
//
// ⚠ The four routes below pre-date the ownership split and were written
// by Vishwajeet. They are live in both web and mobile — do not change
// their paths or response shapes. Phase 1 (usernames, search) is added
// underneath them. Mounted at BOTH /api/user (legacy) and /api/users.
import express from 'express';
import multer from 'multer';
import { getDashboardData, updateProfile, updateAvatar, getPublicProfile} from './user.controller.js';

const router = express.Router();

// Configure multer to store file in memory (buffer) temporarily
const upload = multer({ storage: multer.memoryStorage() });

// GET /api/user/:userId/dashboard
router.get('/:userId/dashboard', getDashboardData);

// PUT /api/user/:userId/profile
router.put('/:userId/profile', updateProfile);

// POST /api/user/:userId/avatar -> New route for handling image uploads
router.post('/:userId/avatar', upload.single('avatar'), updateAvatar);

// Public Profile
router.get('/:userId/public', getPublicProfile);

export default router;