// backend/src/utils/notify.js
// ══════════════════════════════════════════════
// OWNER: VISHWAJEET   —   built in Phase 0
// Neeraj: do not edit this file.
// ══════════════════════════════════════════════
//
// ⛔ FROZEN. One line at each call site emits a notification (§5.2).
//
//   await notify({ userId: post.author_id, actorId: req.user.id,
//                  type: 'post_reply', entityType: 'post', entityId: parentId });
//
// A failed notification must never break the action that triggered it,
// so this function NEVER throws and NEVER returns an error — every
// failure is logged and swallowed. Call it without try/catch.
//
// NOT LIVE YET. `notifications` and `is_blocked_pair()` arrive in
// migration 006. Until then every call is a no-op that logs one warning
// per process. Wiring call sites now is safe and expected.
import { supabase } from '../config/supabase.js';

// Postgres "does not exist" plus the PostgREST schema-cache equivalents.
// 42P01 undefined_table · 42883 undefined_function
// PGRST202 function not found · PGRST205 table not found
const NOT_MIGRATED_YET = new Set(['42P01', '42883', 'PGRST202', 'PGRST205']);

const isNotMigratedYet = (error) => NOT_MIGRATED_YET.has(error?.code);

// One warning per missing object per process, not one per notification.
const alreadyWarned = new Set();
function warnMissing(what, error) {
  if (alreadyWarned.has(what)) return;
  alreadyWarned.add(what);
  console.warn(
    `[notify] ${what} does not exist yet (${error.code}). ` +
    `Notifications are a no-op until migration 006 is applied.`
  );
}

export async function notify({ userId, actorId, type, entityType, entityId }) {
  try {
    if (!userId) return;                                  // nothing to notify
    if (userId === actorId) return;                       // never notify yourself

    const { data: blocked, error: blockError } = await supabase.rpc(
      'is_blocked_pair', { p_a: userId, p_b: actorId }
    );

    if (blockError) {
      if (!isNotMigratedYet(blockError)) {
        // A real failure. Fail closed — we cannot prove these two aren't
        // blocked, and notifying a blocker is worse than staying silent.
        console.error('[notify] is_blocked_pair failed, skipping:', blockError);
        return;
      }
      // Not migrated yet: no blocks table means nobody is blocked. Continue.
      warnMissing('is_blocked_pair()', blockError);
    } else if (blocked) {
      return;                                             // blocked users generate nothing
    }

    const { error: insertError } = await supabase.from('notifications').upsert(
      { user_id: userId, actor_id: actorId, type, entity_type: entityType, entity_id: entityId },
      { onConflict: 'user_id,actor_id,type,entity_id', ignoreDuplicates: true }
    );

    if (insertError) {
      if (isNotMigratedYet(insertError)) warnMissing('the notifications table', insertError);
      else console.error('[notify] insert failed:', insertError);
    }
  } catch (err) {
    // Last line of defence. The caller's action has already succeeded.
    console.error('[notify] unexpected failure, ignored:', err);
  }
}

export default notify;
