// backend/src/utils/respond.js
// ══════════════════════════════════════════════
// OWNER: VISHWAJEET   —   built in Phase 0
// Neeraj: do not edit this file.
// ══════════════════════════════════════════════
//
// ⛔ FROZEN. Every module returns errors and pages through these three
// helpers. If you need a new error code or a different envelope,
// message Vishwajeet — do not hand-roll a shape in your own module.

export function sendError(res, status, code, extra = {}) {
  return res.status(status).json({ error: code, ...extra });
}

/** Maps a Postgres/Supabase error to our standard response. */
export function mapDbError(res, error) {
  if (error.code === '23505') return sendError(res, 400, 'DUPLICATE');
  if (error.code === '23503') return sendError(res, 400, 'INVALID_REFERENCE');

  // Our triggers RAISE EXCEPTION with these names.
  const raised = [
    'USERNAME_RESERVED', 'BLOCKED', 'NESTED_REPLY_NOT_ALLOWED',
    'RATE_LIMIT_POSTS', 'RATE_LIMIT_REPLIES',
    'POSTING_RESTRICTED', 'ACCOUNT_SUSPENDED',
  ].find(name => error.message?.includes(name));

  if (raised) {
    const status = raised.startsWith('RATE_LIMIT') ? 429
                 : raised === 'BLOCKED' ? 403 : 400;
    return sendError(res, status, raised);
  }

  console.error('[db]', error);
  return sendError(res, 500, 'INTERNAL_ERROR');
}

/** Standard cursor-paginated envelope. Every list endpoint returns this shape. */
export function sendPage(res, items, cursorField = 'created_at', limit = 20) {
  const next = items.length === limit ? items[items.length - 1][cursorField] : null;
  return res.json({ items, next_cursor: next });
}
