// backend/src/modules/share/share.routes.js
// ══════════════════════════════════════════════
// OWNER: VISHWAJEET   —   added 18 Sep 2026
// Neeraj: do not edit this file.
// ══════════════════════════════════════════════

import { Router } from 'express';
import { shareProduct } from './share.controller.js';

const router = Router();

// Mounted at /share (NOT /api) in app.js. These routes return HTML, not JSON —
// they are what a link-preview crawler fetches, and the path ends up visible in
// WhatsApp, so it reads as a URL rather than as an API call.
//
// No auth, by design: a crawler carries no token, and everything rendered is
// already public on the cross-campus browse feed.
router.get('/product/:id', shareProduct);

export default router;
