// backend/src/modules/university/university.routes.js
// ══════════════════════════════════════════════
// OWNER: VISHWAJEET   —   existing module
// Neeraj: do not edit this file.
// ══════════════════════════════════════════════
import express from 'express';
import { getUniversities } from './university.controller.js';

const router = express.Router();

router.get('/', getUniversities);

export default router;