// backend/src/modules/messages/messages.routes.js
// ══════════════════════════════════════════════
// OWNER: VISHWAJEET   —   existing module
// Neeraj: do not edit this file.
// ══════════════════════════════════════════════
import express from 'express';
import { getInbox, getChatHistory, sendMessage, markAsRead, markAsDelivered} from './messages.controller.js';
import requireAuth from '../../middleware/requireAuth.js';

const router = express.Router();

// 🔒 requireAuth on EVERY route in this module (Phase 4 Block V-A).
//
// Four of the five took the acting user from the request — `:userId` in the
// path on /inbox, `sender_id` / `userId` in the body on the other three — so a
// caller with no account at all could read any student's inbox, send a message
// that appeared to come from a real student, or mark someone else's threads
// read. The actor is now `req.user.id` and nothing else; a caller-supplied id
// is IGNORED IN SILENCE rather than rejected, because both clients still send
// one today and a 400 would break them for no security gain.
//
// The path parameter on /inbox stays in the URL — both clients build it — but
// the handler compares it to the token and returns 403 rather than trusting it.
//
// ⚠️ BREAKING for the web app: frontend/ sends no Authorization header on
// /inbox, /send, /read or /deliver yet and gets 401 until it does. Mobile
// attaches a token to every request (mobile/src/lib/api.ts) and is unaffected.
// See docs/CHANGELOG.md.
router.get('/inbox/:userId', requireAuth, getInbox);

// getChatHistory verifies that req.user.id is one of the two parties in the
// thread, which is only meaningful once the token has been verified — without
// requireAuth, req.user is undefined and every read of a legitimate
// conversation would be rejected.
router.get('/history', requireAuth, getChatHistory);
router.post('/send', requireAuth, sendMessage);
router.put('/read', requireAuth, markAsRead);
router.put('/deliver', requireAuth, markAsDelivered);

export default router;
