// backend/src/middleware/optionalAuth.js
// ══════════════════════════════════════════════
// OWNER: VISHWAJEET   —   built in Phase 0
// Neeraj: do not edit this file.
// ══════════════════════════════════════════════
//
// ⛔ FROZEN. For routes that must work both signed in and signed out —
// public profiles, the username availability check, global feeds.
//
// This middleware NEVER rejects. `req.user` is always set: the Supabase
// auth user when a valid Bearer token is present, otherwise `null`. A
// bad, expired or absent token all produce `null` and the request
// continues. Handlers branch on `if (req.user)`, and must not assume a
// caller exists.
//
//   import optionalAuth from '../../middleware/optionalAuth.js';
//   router.get('/:username', optionalAuth, getProfile);
import { supabase } from '../config/supabase.js';

export async function optionalAuth(req, res, next) {
  req.user = null;

  try {
    const header = req.headers.authorization || '';
    const token = header.startsWith('Bearer ') ? header.slice(7).trim() : null;

    if (token) {
      const { data, error } = await supabase.auth.getUser(token);
      if (!error && data?.user) req.user = data.user;
    }
  } catch (err) {
    // Deliberately swallowed: an unreachable auth server must not turn a
    // public page into a 500. The caller is simply treated as anonymous.
    console.warn('[optionalAuth] token check failed, continuing anonymous:', err.message);
  }

  return next();
}

export default optionalAuth;
