// backend/src/middleware/requireAuth.js
// ══════════════════════════════════════════════
// OWNER: VISHWAJEET   —   built in Phase 0
// Neeraj: do not edit this file.
// ══════════════════════════════════════════════
//
// ⛔ FROZEN. Put this in front of any route that must have a logged-in
// caller. On success `req.user` is the Supabase auth user, so
// `req.user.id` is the caller's UUID — use that, never a body field.
//
//   import requireAuth from '../../middleware/requireAuth.js';
//   router.post('/:id/follow', requireAuth, followUser);
import { supabase } from '../config/supabase.js';
import { sendError } from '../utils/respond.js';

export async function requireAuth(req, res, next) {
  const header = req.headers.authorization || '';
  const token = header.startsWith('Bearer ') ? header.slice(7).trim() : null;

  if (!token) return sendError(res, 401, 'UNAUTHORIZED');

  try {
    const { data, error } = await supabase.auth.getUser(token);
    if (error || !data?.user) return sendError(res, 401, 'UNAUTHORIZED');

    req.user = data.user;
    return next();
  } catch (err) {
    console.error('[requireAuth]', err);
    return sendError(res, 401, 'UNAUTHORIZED');
  }
}

export default requireAuth;
