// backend/src/modules/social/social.routes.js
// ══════════════════════════════════════════════
// OWNER: NEERAJ   —   built in Phase 3
// Vishwajeet: do not edit this file.
// ══════════════════════════════════════════════
import { Router } from 'express';

const router = Router();

// Follows, blocks and privacy. Mounted at /api/users in app.js, after
// userRoutes — Express falls through to this router when no path in
// user.routes.js matches. Add Phase 3 routes here; never in app.js.

export default router;
