// backend/src/modules/posts/posts.routes.js
// ══════════════════════════════════════════════
// OWNER: VISHWAJEET   —   built in Phase 6
// Neeraj: do not edit this file.
// ══════════════════════════════════════════════
import { Router } from 'express';

const router = Router();

// Community feeds, posts, replies and post likes. Mounted at /api/posts
// in app.js. The three feed endpoints stay with Vishwajeet even if the
// load valve moves the write endpoints. Add Phase 6 routes here.

export default router;
